networks:
  pretix:
    driver: bridge
    internal: false

services:
  phpfpm:
    environment:
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - ./dpl-cms:/app

  nginx:
    volumes:
      - ./dpl-cms:/app

  pretix:
    image: pretix/standalone:latest
    profiles:
      - pretix
    networks:
      - app
      - pretix
      - frontend
    depends_on:
      - pretix_database
      - pretix_redis
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/pretix/etc/pretix.cfg:/etc/pretix/pretix.cfg
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pretix.rule=Host(`pretix.${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pretix-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pretix-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pretix.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_pretix.loadbalancer.server.port=80"
    environment:
      # https://docs.pretix.eu/en/latest/admin/config.html#configuration-file
      - PRETIX_PRETIX_INSTANCE_NAME=${PRETIX_PRETIX_INSTANCE_NAME}
      - PRETIX_PRETIX_URL=${PRETIX_PRETIX_URL}

  pretix_database:
    # https://hub.docker.com/_/postgres
    image: postgres
    profiles:
      - pretix
    networks:
      - pretix
    ports:
      - '3306'
    volumes:
      # - .docker/pretix/dumps:/docker-entrypoint-initdb.d
      - .docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
      - POSTGRES_DATABASE=pretix

  pretix_redis:
    image: redis:latest
    profiles:
      - pretix
    networks:
      - pretix
    ports:
      - "6379"
