#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
project_dir=$(cd $(dirname "$script_dir") && pwd)
bold=$(tput -Txterm-256color bold)
normal=$(tput -Txterm-256color sgr0)


read -p "This will reset your setup. Continue? ([yN])? " -n 1 -r
echo
if ! [[ $REPLY =~ ^[Yy]$ ]]; then
  exit 1
fi

function compose() {
    docker compose "$@"
}

function drush() {
    compose exec phpfpm vendor/bin/drush "$@"
}

compose pull
compose up --detach --build

# @todo resolve `sh: 1: [[: not found` error due to `"post-drupal-scaffold-cmd"` in composer.json.
# Make `sh` point to `bash` (rather than `dash` which is the default in Ubuntu)
#compose exec --user root phpfpm bash -c 'ln -sf bash /bin/sh'
compose exec phpfpm composer install

git clone --branch develop https://github.com/danskernesdigitalebibliotek/dpl-cms dpl-cms
git clone --branch dpl_pretix https://github.com/rimi-itk/dpl_pretix dpl-cms/web/sites/default/files/modules_local/dpl_pretix

cat >| dpl-cms/web/sites/default/settings.local.php <<'EOF'
<?php

$settings['hash_salt'] = 'V-tz1Y86bnQ7IDugaKTbx0goQR64ewhdsWlscc00813DSYYuEf9ziG2Qqfo1zshlVQF_n37Lbg';

$databases['default']['default'] = [
  'database' => getenv('DATABASE_DATABASE') ?: 'db',
  'username' => getenv('DATABASE_USERNAME') ?: 'db',
  'password' => getenv('DATABASE_PASSWORD') ?: 'db',
  'host' => getenv('DATABASE_HOST') ?: 'mariadb',
  'port' => getenv('DATABASE_PORT') ?: '',
  'driver' => getenv('DATABASE_DRIVER') ?: 'mysql',
  'prefix' => '',
];
EOF

drush --yes site:install --existing-config
drush --yes cache:rebuild
drush --yes pm:uninstall purge
drush --yes pm:install devel dpl_example_content dpl_example_breadcrumb field_ui restui uuid_url views_ui dblog

drush --yes pm:install dpl_pretix

open $(drush --uri=$(itkdev-docker-compose url) user:login /admin/config/dpl_pretix)

drush --yes config:set dpl_pretix.settings pretix.url http://pretix.dpl-cms-develop.local.itkdev.dk/
drush --yes config:set dpl_pretix.settings pretix.organizer_slug dpl-cms
# http://pretix.dpl-cms-develop.local.itkdev.dk/control/organizer/dpl-cms/team/1/
drush --yes config:set dpl_pretix.settings pretix.api_key p1q35ojjgt7jh3wqoub00v5l0v91xf94pjn0l708zmcz40ec1i7a6eilrjhrle1i
drush --yes config:set dpl_pretix.settings pretix.template_event_slug dpl-cms-default-template

drush config:get dpl_pretix.settings
